### ISSUE TITLE
جاموندن یه خط در ترجمه فصل دوم - Postgres

### ISSUE THREAD

**Issue by amir69prog** [mthri/dfp-persian#117]
در ترجمه فصل دوم توی بخش پستگرس طبق کتاب انگلیسی که بنده دارم یه خط جامونده 
باید ترجمه به این شکل باشد به نظرم
‍‍
### docker-compose.yml
```
version: '3.8'
services:
  web:
    build: .
        command: python /code/manage.py runserver 0.0.0.0:8000
    volumes:
        - .:/code
    ports:
        - 8000:8000
    depends_on:
        - db
  db:
    image: postgres:11
    environment:
        - "POSTGRES_HOST_AUTH_METHOD=trust" # this line is left
```
که خط آخر در ترجمه ها نیومده
